const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

const ORDER_DELIVERED_REQUEST = 'ORDER_DELIVERED_REQUEST';
const ORDER_DELIVERED_SUCCESS = 'ORDER_DELIVERED_SUCCESS';
const ORDER_DELIVERED_FAIL = 'ORDER_DELIVERED_FAIL';

const ORDER_TYPES = {
  ORDER_LIST_REQUEST,
  ORDER_LIST_SUCCESS,
  ORDER_LIST_FAIL,
  ORDER_DETAILS_REQUEST,
  ORDER_DETAILS_SUCCESS,
  ORDER_DETAILS_FAIL,
  ORDER_DELIVERED_REQUEST,
  ORDER_DELIVERED_SUCCESS,
  ORDER_DELIVERED_FAIL,
};

export default ORDER_TYPES;
