const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
const USER_LOGOUT = 'USER_LOGOUT';

const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
const USER_LIST_FAIL = 'USER_LIST_FAIL';
const USER_LIST_RESET = 'USER_LIST_RESET';

const USER_STAT_REQUEST = 'USER_STAT_REQUEST';
const USER_STAT_SUCCESS = 'USER_STAT_SUCCESS';
const USER_STAT_FAIL = 'USER_STAT_FAIL';

const USER_TYPES = {
  USER_LOGIN_REQUEST,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FAIL,
  USER_LOGOUT,
  USER_LIST_REQUEST,
  USER_LIST_SUCCESS,
  USER_LIST_FAIL,
  USER_LIST_RESET,
  USER_STAT_REQUEST,
  USER_STAT_SUCCESS,
  USER_STAT_FAIL,
};
export default USER_TYPES;
